name: mobile_pos
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  dio: 4.0.6
  intl: 0.17.0
  google_fonts: 2.3.1
  hive: 2.1.0
  build_runner: 2.1.9
  hive_generator: 1.1.2
  path_provider: 2.0.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

